// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas automatizadas de IU.
//      Versión: 15.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace StartGrow.UIT
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UILoginStartGrowInternWindow UILoginStartGrowInternWindow
        {
            get
            {
                if ((this.mUILoginStartGrowInternWindow == null))
                {
                    this.mUILoginStartGrowInternWindow = new UILoginStartGrowInternWindow();
                }
                return this.mUILoginStartGrowInternWindow;
            }
        }
        
        public UISeleccionelosproyectWindow UISeleccionelosproyectWindow
        {
            get
            {
                if ((this.mUISeleccionelosproyectWindow == null))
                {
                    this.mUISeleccionelosproyectWindow = new UISeleccionelosproyectWindow();
                }
                return this.mUISeleccionelosproyectWindow;
            }
        }
        #endregion
        
        #region Fields
        private UILoginStartGrowInternWindow mUILoginStartGrowInternWindow;
        
        private UISeleccionelosproyectWindow mUISeleccionelosproyectWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UILoginStartGrowInternWindow : BrowserWindow
    {
        
        public UILoginStartGrowInternWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Log in - StartGrow";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Log in - StartGrow");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UILoginStartGrowDocument UILoginStartGrowDocument
        {
            get
            {
                if ((this.mUILoginStartGrowDocument == null))
                {
                    this.mUILoginStartGrowDocument = new UILoginStartGrowDocument(this);
                }
                return this.mUILoginStartGrowDocument;
            }
        }
        
        public UILoginStartGrowDocument1 UILoginStartGrowDocument1
        {
            get
            {
                if ((this.mUILoginStartGrowDocument1 == null))
                {
                    this.mUILoginStartGrowDocument1 = new UILoginStartGrowDocument1(this);
                }
                return this.mUILoginStartGrowDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UILoginStartGrowDocument mUILoginStartGrowDocument;
        
        private UILoginStartGrowDocument1 mUILoginStartGrowDocument1;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UILoginStartGrowDocument : HtmlDocument
    {
        
        public UILoginStartGrowDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log in - StartGrow";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:60421/Account/Login";
            this.WindowTitles.Add("Log in - StartGrow");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"form-control\" id=\"Em";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIEmailEdit.WindowTitles.Add("Log in - StartGrow");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlButton(this);
                    #region Criterio de búsqueda
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Log in";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\"";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUILoginButton.WindowTitles.Add("Log in - StartGrow");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Criterio de búsqueda
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log in";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:60421/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Account/Login\"";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "6";
                    this.mUILoginHyperlink.WindowTitles.Add("Log in - StartGrow");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIEmailEdit;
        
        private HtmlButton mUILoginButton;
        
        private HtmlHyperlink mUILoginHyperlink;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UILoginStartGrowDocument1 : HtmlDocument
    {
        
        public UILoginStartGrowDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log in - StartGrow";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:60421/Account/Login?ReturnUrl=%2F";
            this.WindowTitles.Add("Log in - StartGrow");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control valid";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"form-control valid\" ";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIEmailEdit.WindowTitles.Add("Log in - StartGrow");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlButton(this);
                    #region Criterio de búsqueda
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Log in";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\"";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUILoginButton.WindowTitles.Add("Log in - StartGrow");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Criterio de búsqueda
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log in";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:60421/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Account/Login\"";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "6";
                    this.mUILoginHyperlink.WindowTitles.Add("Log in - StartGrow");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIEmailEdit;
        
        private HtmlButton mUILoginButton;
        
        private HtmlHyperlink mUILoginHyperlink;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UISeleccionelosproyectWindow : BrowserWindow
    {
        
        public UISeleccionelosproyectWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Seleccione los proyectos que vaya a publicar - StartGrow";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Seleccione los proyectos que vaya a publicar - StartGrow");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UISeleccionelosproyectDocument UISeleccionelosproyectDocument
        {
            get
            {
                if ((this.mUISeleccionelosproyectDocument == null))
                {
                    this.mUISeleccionelosproyectDocument = new UISeleccionelosproyectDocument(this);
                }
                return this.mUISeleccionelosproyectDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISeleccionelosproyectDocument mUISeleccionelosproyectDocument;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UISeleccionelosproyectDocument : HtmlDocument
    {
        
        public UISeleccionelosproyectDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Seleccione los proyectos que vaya a publicar - StartGrow";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:60421/";
            this.WindowTitles.Add("Seleccione los proyectos que vaya a publicar - StartGrow");
            #endregion
        }
        
        #region Properties
        public HtmlCheckBox UIAreasSeleccionadaCheckBox
        {
            get
            {
                if ((this.mUIAreasSeleccionadaCheckBox == null))
                {
                    this.mUIAreasSeleccionadaCheckBox = new HtmlCheckBox(this);
                    #region Criterio de búsqueda
                    this.mUIAreasSeleccionadaCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Id] = null;
                    this.mUIAreasSeleccionadaCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "areasSeleccionada";
                    this.mUIAreasSeleccionadaCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.Value] = "Salud";
                    this.mUIAreasSeleccionadaCheckBox.SearchProperties[HtmlCheckBox.PropertyNames.LabeledBy] = null;
                    this.mUIAreasSeleccionadaCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIAreasSeleccionadaCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.Class] = null;
                    this.mUIAreasSeleccionadaCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "name=\"areasSeleccionada\" type=\"checkbox\"";
                    this.mUIAreasSeleccionadaCheckBox.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "3";
                    this.mUIAreasSeleccionadaCheckBox.WindowTitles.Add("Seleccione los proyectos que vaya a publicar - StartGrow");
                    #endregion
                }
                return this.mUIAreasSeleccionadaCheckBox;
            }
        }
        
        public HtmlCheckBox UIAreasSeleccionadaCheckBox1
        {
            get
            {
                if ((this.mUIAreasSeleccionadaCheckBox1 == null))
                {
                    this.mUIAreasSeleccionadaCheckBox1 = new HtmlCheckBox(this);
                    #region Criterio de búsqueda
                    this.mUIAreasSeleccionadaCheckBox1.SearchProperties[HtmlCheckBox.PropertyNames.Id] = null;
                    this.mUIAreasSeleccionadaCheckBox1.SearchProperties[HtmlCheckBox.PropertyNames.Name] = "areasSeleccionada";
                    this.mUIAreasSeleccionadaCheckBox1.SearchProperties[HtmlCheckBox.PropertyNames.Value] = "Drogería";
                    this.mUIAreasSeleccionadaCheckBox1.SearchProperties[HtmlCheckBox.PropertyNames.LabeledBy] = null;
                    this.mUIAreasSeleccionadaCheckBox1.FilterProperties[HtmlCheckBox.PropertyNames.Title] = null;
                    this.mUIAreasSeleccionadaCheckBox1.FilterProperties[HtmlCheckBox.PropertyNames.Class] = null;
                    this.mUIAreasSeleccionadaCheckBox1.FilterProperties[HtmlCheckBox.PropertyNames.ControlDefinition] = "name=\"areasSeleccionada\" type=\"checkbox\"";
                    this.mUIAreasSeleccionadaCheckBox1.FilterProperties[HtmlCheckBox.PropertyNames.TagInstance] = "5";
                    this.mUIAreasSeleccionadaCheckBox1.WindowTitles.Add("Seleccione los proyectos que vaya a publicar - StartGrow");
                    #endregion
                }
                return this.mUIAreasSeleccionadaCheckBox1;
            }
        }
        
        public HtmlEdit UINombredelproyectoEdit
        {
            get
            {
                if ((this.mUINombredelproyectoEdit == null))
                {
                    this.mUINombredelproyectoEdit = new HtmlEdit(this);
                    #region Criterio de búsqueda
                    this.mUINombredelproyectoEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "nombreProyecto";
                    this.mUINombredelproyectoEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "nombreProyecto";
                    this.mUINombredelproyectoEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Nombre del proyecto";
                    this.mUINombredelproyectoEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINombredelproyectoEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINombredelproyectoEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUINombredelproyectoEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"nombreProyecto\" id=\"nombreProyecto";
                    this.mUINombredelproyectoEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUINombredelproyectoEdit.WindowTitles.Add("Seleccione los proyectos que vaya a publicar - StartGrow");
                    #endregion
                }
                return this.mUINombredelproyectoEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCheckBox mUIAreasSeleccionadaCheckBox;
        
        private HtmlCheckBox mUIAreasSeleccionadaCheckBox1;
        
        private HtmlEdit mUINombredelproyectoEdit;
        #endregion
    }
}
